-- Nexus full restore schema (generated by backup_supabase.py)
-- Run this in the NEW Supabase project SQL Editor FIRST, then restore_data.sql

-- XYTEEE Nexus – Supabase PostgreSQL Schema
-- Run this in Supabase → SQL Editor
-- Safe to rerun: drops all tables first, then recreates cleanly.

-- ── Drop everything (CASCADE handles FK dependencies) ──────────────
DROP TABLE IF EXISTS notifications   CASCADE;
DROP TABLE IF EXISTS reports         CASCADE;
DROP TABLE IF EXISTS stories         CASCADE;
DROP TABLE IF EXISTS messages        CASCADE;
DROP TABLE IF EXISTS conversations   CASCADE;
DROP TABLE IF EXISTS blocks          CASCADE;
DROP TABLE IF EXISTS friendships     CASCADE;
DROP TABLE IF EXISTS friend_requests CASCADE;
DROP TABLE IF EXISTS user_sessions   CASCADE;
DROP TABLE IF EXISTS users           CASCADE;

-- ── Users ──────────────────────────────────────────────────────────
CREATE TABLE users (
  user_id               TEXT        PRIMARY KEY,
  email                 TEXT        UNIQUE NOT NULL,
  username              TEXT        UNIQUE NOT NULL,
  display_name          TEXT        NOT NULL,
  password_hash         TEXT,
  bio                   TEXT        DEFAULT '',
  profile_picture       TEXT        DEFAULT '',
  cover_picture         TEXT        DEFAULT '',
  is_private            BOOLEAN     DEFAULT FALSE,
  email_verified        BOOLEAN     DEFAULT FALSE,
  email_verify_token    TEXT,
  password_reset_token  TEXT,
  password_reset_expiry TIMESTAMPTZ,
  provider              TEXT        DEFAULT 'email',
  online                BOOLEAN     DEFAULT FALSE,
  last_seen             TIMESTAMPTZ DEFAULT NOW(),
  created_at            TIMESTAMPTZ DEFAULT NOW(),
  badge_type            TEXT        DEFAULT NULL   -- blue|gold|gray (admin-assigned verified badge)
);

-- ── Sessions ───────────────────────────────────────────────────────
CREATE TABLE user_sessions (
  session_token TEXT        PRIMARY KEY,
  user_id       TEXT        NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  expires_at    TIMESTAMPTZ NOT NULL,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ── Friend requests ────────────────────────────────────────────────
CREATE TABLE friend_requests (
  request_id  TEXT        PRIMARY KEY,
  from_user   TEXT        NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  to_user     TEXT        NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  status      TEXT        DEFAULT 'pending',   -- pending | accepted | rejected
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  resolved_at TIMESTAMPTZ
);

-- ── Friendships ────────────────────────────────────────────────────
-- a < b always (sorted), so each pair is stored exactly once
CREATE TABLE friendships (
  friendship_id TEXT        PRIMARY KEY,
  a             TEXT        NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  b             TEXT        NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(a, b),
  CHECK (a < b)
);

-- ── Blocks ─────────────────────────────────────────────────────────
CREATE TABLE blocks (
  blocker    TEXT        NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  blocked    TEXT        NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY(blocker, blocked)
);

-- ── Conversations ──────────────────────────────────────────────────
CREATE TABLE conversations (
  conversation_id TEXT        PRIMARY KEY,
  participants    TEXT[]      NOT NULL DEFAULT '{}',
  last_message    TEXT,
  last_message_at TIMESTAMPTZ DEFAULT NOW(),
  deleted_for     TEXT[]      DEFAULT '{}',
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- ── Messages ───────────────────────────────────────────────────────
CREATE TABLE messages (
  message_id           TEXT        PRIMARY KEY,
  conversation_id      TEXT        NOT NULL REFERENCES conversations(conversation_id) ON DELETE CASCADE,
  sender_id            TEXT        NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  content              TEXT        DEFAULT '',
  kind                 TEXT        DEFAULT 'text',
  media                TEXT,
  file_name            TEXT,
  reply_to             TEXT,
  edited               BOOLEAN     DEFAULT FALSE,
  deleted_for_everyone BOOLEAN     DEFAULT FALSE,
  deleted_for          TEXT[]      DEFAULT '{}',
  read_by              TEXT[]      DEFAULT '{}',
  delivered_to         TEXT[]      DEFAULT '{}',
  reactions            JSONB       DEFAULT '[]',
  pinned_for           TEXT[]      DEFAULT '{}',
  created_at           TIMESTAMPTZ DEFAULT NOW()
);

-- ── Stories ────────────────────────────────────────────────────────
CREATE TABLE stories (
  story_id   TEXT        PRIMARY KEY,
  user_id    TEXT        NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  kind       TEXT        DEFAULT 'image',
  media      TEXT        NOT NULL,
  caption    TEXT        DEFAULT '',
  is_private BOOLEAN     DEFAULT FALSE,
  media_x    FLOAT       DEFAULT 0.0,
  media_y    FLOAT       DEFAULT 0.0,
  text_x     FLOAT       DEFAULT 0.08,
  text_y     FLOAT       DEFAULT 0.38,
  text_color TEXT        DEFAULT '#FFFFFF',
  text_size  INTEGER     DEFAULT 28,
  font_index INTEGER     DEFAULT 0,
  media_scale FLOAT      DEFAULT 1.0,
  music_id   TEXT        DEFAULT NULL,
  viewers    JSONB       DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL
);

-- ── Notifications ──────────────────────────────────────────────────
CREATE TABLE notifications (
  notif_id   TEXT        PRIMARY KEY,
  user_id    TEXT        NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  kind       TEXT        NOT NULL,
  data       JSONB       DEFAULT '{}',
  read       BOOLEAN     DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ── Reports ────────────────────────────────────────────────────────
CREATE TABLE reports (
  report_id       TEXT        PRIMARY KEY,
  reporter_id     TEXT        NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  reported_id     TEXT        NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  conversation_id TEXT,
  category        TEXT        NOT NULL,
  description     TEXT        DEFAULT '',
  status          TEXT        DEFAULT 'pending',   -- pending | actioned | dismissed
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  resolved_at     TIMESTAMPTZ,
  resolved_by     TEXT
);

-- ── Indexes ────────────────────────────────────────────────────────
CREATE INDEX idx_messages_conv_created
  ON messages(conversation_id, created_at DESC);

CREATE INDEX idx_notifications_user_created
  ON notifications(user_id, created_at DESC);

CREATE INDEX idx_stories_user_expires
  ON stories(user_id, expires_at);

CREATE INDEX idx_friend_requests_to_status
  ON friend_requests(to_user, status);

CREATE INDEX idx_friend_requests_from_status
  ON friend_requests(from_user, status);

CREATE INDEX idx_conversations_participants
  ON conversations USING GIN(participants);

CREATE INDEX idx_messages_deleted_for
  ON messages USING GIN(deleted_for);

CREATE INDEX idx_messages_read_by
  ON messages USING GIN(read_by);

CREATE INDEX idx_reports_status_created
  ON reports(status, created_at DESC);

CREATE INDEX idx_reports_reported
  ON reports(reported_id, created_at DESC);

-- ── Disable RLS (service-role key bypasses RLS anyway) ────────────
ALTER TABLE users           DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_sessions   DISABLE ROW LEVEL SECURITY;
ALTER TABLE friend_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE friendships     DISABLE ROW LEVEL SECURITY;
ALTER TABLE blocks          DISABLE ROW LEVEL SECURITY;
ALTER TABLE conversations   DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages        DISABLE ROW LEVEL SECURITY;
ALTER TABLE stories         DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications   DISABLE ROW LEVEL SECURITY;
ALTER TABLE reports         DISABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS circles (
  circle_id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT DEFAULT '',
  photo TEXT,
  owner_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  privacy TEXT NOT NULL DEFAULT 'public'
    CHECK (privacy IN ('public', 'private')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS circle_members (
  circle_id TEXT NOT NULL REFERENCES circles(circle_id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'member'
    CHECK (role IN ('owner', 'admin', 'member')),
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (circle_id, user_id)
);

CREATE TABLE IF NOT EXISTS circle_invites (
  invite_id TEXT PRIMARY KEY,
  circle_id TEXT NOT NULL REFERENCES circles(circle_id) ON DELETE CASCADE,
  created_by TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  invite_code TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS circle_join_requests (
  request_id TEXT PRIMARY KEY,
  circle_id TEXT NOT NULL REFERENCES circles(circle_id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (circle_id, user_id)
);

CREATE TABLE IF NOT EXISTS circle_messages (
  message_id TEXT PRIMARY KEY,
  circle_id TEXT NOT NULL REFERENCES circles(circle_id) ON DELETE CASCADE,
  sender_id TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  content TEXT DEFAULT '',
  kind TEXT DEFAULT 'text',
  media TEXT,
  reply_to TEXT,
  edited BOOLEAN DEFAULT FALSE,
  deleted_for_everyone BOOLEAN DEFAULT FALSE,
  read_by TEXT[] DEFAULT '{}',
  reactions JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_circle_members_user
  ON circle_members(user_id);

CREATE INDEX IF NOT EXISTS idx_circle_messages_created
  ON circle_messages(circle_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_circle_join_requests
  ON circle_join_requests(circle_id, status);

ALTER TABLE circles DISABLE ROW LEVEL SECURITY;
ALTER TABLE circle_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE circle_invites DISABLE ROW LEVEL SECURITY;
ALTER TABLE circle_join_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE circle_messages DISABLE ROW LEVEL SECURITY;

-- push_tokens (added after original schema) --------------------
CREATE TABLE IF NOT EXISTS push_tokens (
  user_id          TEXT NOT NULL,
  expo_push_token  TEXT NOT NULL,
  device_name      TEXT,
  created_at       TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, expo_push_token)
);
ALTER TABLE push_tokens DISABLE ROW LEVEL SECURITY;

-- appeals (added after original schema) ------------------------
CREATE TABLE IF NOT EXISTS appeals (
  appeal_id          TEXT PRIMARY KEY,
  user_id            TEXT NOT NULL,
  name               TEXT DEFAULT '',
  email              TEXT DEFAULT '',
  message            TEXT DEFAULT '',
  suspension_reason  TEXT,
  status             TEXT DEFAULT 'pending',
  created_at         TIMESTAMPTZ DEFAULT NOW(),
  reviewed_at        TIMESTAMPTZ,
  reviewed_by        TEXT
);
ALTER TABLE appeals DISABLE ROW LEVEL SECURITY;

-- Columns added after the original schema (ALTER patches) ------
ALTER TABLE appeals ADD COLUMN IF NOT EXISTS appeal_id TEXT;
ALTER TABLE appeals ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE appeals ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE appeals ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE appeals ADD COLUMN IF NOT EXISTS message TEXT;
ALTER TABLE appeals ADD COLUMN IF NOT EXISTS suspension_reason TEXT;
ALTER TABLE appeals ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE appeals ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE appeals ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ;
ALTER TABLE appeals ADD COLUMN IF NOT EXISTS reviewed_by TEXT;
ALTER TABLE blocks ADD COLUMN IF NOT EXISTS id BIGSERIAL;
ALTER TABLE circles ADD COLUMN IF NOT EXISTS theme TEXT;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS kind TEXT;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS circle_name TEXT;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS circle_photo TEXT;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS circle_admins TEXT[];
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS circle_description TEXT;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS circle_settings JSONB;
ALTER TABLE push_tokens ADD COLUMN IF NOT EXISTS user_id TEXT;
ALTER TABLE push_tokens ADD COLUMN IF NOT EXISTS expo_push_token TEXT;
ALTER TABLE push_tokens ADD COLUMN IF NOT EXISTS device_name TEXT;
ALTER TABLE push_tokens ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE push_tokens ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE stories ADD COLUMN IF NOT EXISTS story_reactions JSONB;
ALTER TABLE user_sessions ADD COLUMN IF NOT EXISTS id BIGSERIAL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS verified BOOLEAN;
ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_type TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS expo_push_token TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS verified_since TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS status_text TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS status_expires_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS online_status TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS moderation_status TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS moderation_reason TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS moderation_reason_code TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS moderated_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS moderated_by TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS birthday DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS birthday_visibility TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS badge_icon TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS badge_expires_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_frame TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS achievement_level TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_animation TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_animation_speed TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_animation_intensity TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_animation_expires_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_push_tokens_user ON push_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_appeals_user ON appeals(user_id);
