-- Nexus full restore schema (generated by backup_supabase.py)
-- Run this in the NEW Supabase project SQL Editor FIRST, then restore_data.sql

CREATE TABLE users (
  user_id                      TEXT
  email                        TEXT
  username                     TEXT
  display_name                 TEXT
  password_hash                TEXT
  bio                          TEXT
  profile_picture              TEXT
  cover_picture                TEXT
  is_private                   BOOLEAN
  email_verified               BOOLEAN
  email_verify_token           TEXT
  password_reset_token         TEXT
  password_reset_expiry        TIMESTAMPTZ
  provider                     TEXT
  online                       BOOLEAN
  last_seen                    TIMESTAMPTZ
  verified                     BOOLEAN
  verification_type            TEXT
  created_at                   TIMESTAMPTZ
  badge_type                   TEXT
  expo_push_token              TEXT
  verified_since               TIMESTAMPTZ
  status_text                  TEXT
  status_expires_at            TIMESTAMPTZ
  online_status                TEXT
  moderation_status            TEXT
  moderation_reason            TEXT
  moderation_reason_code       TEXT
  moderated_at                 TIMESTAMPTZ
  moderated_by                 TEXT
  birthday                     TEXT
  birthday_visibility          TEXT
  badge_icon                   TEXT
  badge_expires_at             TIMESTAMPTZ
  profile_frame                TEXT
  achievement_level            TEXT
  profile_animation            TEXT
  profile_animation_speed      TEXT
  profile_animation_intensity  TEXT
  profile_animation_expires_at TIMESTAMPTZ,
  PRIMARY KEY (user_id)
);
CREATE UNIQUE INDEX users_email_key ON users(email);
CREATE UNIQUE INDEX users_username_key ON users(username);

CREATE TABLE user_sessions (
  id                           BIGSERIAL
  session_token                TEXT
  user_id                      TEXT
  expires_at                   TIMESTAMPTZ
  created_at                   TIMESTAMPTZ,
  PRIMARY KEY (session_token)
);
CREATE UNIQUE INDEX user_sessions_session_token_key ON user_sessions(session_token);

CREATE TABLE friend_requests (
  request_id                   TEXT
  from_user                    TEXT
  to_user                      TEXT
  status                       TEXT
  created_at                   TIMESTAMPTZ
  resolved_at                  TIMESTAMPTZ,
  PRIMARY KEY (request_id)
);
CREATE INDEX idx_friend_requests_to_status ON friend_requests(to_user, status);
CREATE INDEX idx_friend_requests_from_status ON friend_requests(from_user, status);

CREATE TABLE friendships (
  friendship_id                TEXT
  a                            TEXT
  b                            TEXT
  created_at                   TIMESTAMPTZ,
  PRIMARY KEY (friendship_id)
);
CREATE UNIQUE INDEX friendships_a_key ON friendships(a);
CREATE UNIQUE INDEX friendships_b_key ON friendships(b);

CREATE TABLE blocks (
  id                           BIGSERIAL
  blocker                      TEXT
  blocked                      TEXT
  created_at                   TIMESTAMPTZ,
  PRIMARY KEY (blocker, blocked)
);

CREATE TABLE conversations (
  conversation_id              TEXT
  participants                 TEXT[]
  last_message                 TEXT
  last_message_at              TIMESTAMPTZ
  created_at                   TIMESTAMPTZ
  kind                         TEXT
  circle_name                  TEXT
  circle_photo                 TEXT
  circle_admins                TEXT[]
  circle_description           TEXT
  circle_settings              JSONB
  deleted_for                  TEXT[],
  PRIMARY KEY (conversation_id)
);
CREATE INDEX idx_conversations_participants ON conversations USING GIN(participants);

CREATE TABLE messages (
  message_id                   TEXT
  conversation_id              TEXT
  sender_id                    TEXT
  content                      TEXT
  kind                         TEXT
  media                        TEXT
  file_name                    TEXT
  reply_to                     TEXT
  edited                       BOOLEAN
  deleted_for_everyone         BOOLEAN
  deleted_for                  TEXT[]
  read_by                      TEXT[]
  delivered_to                 TEXT[]
  reactions                    JSONB
  pinned_for                   TEXT[]
  created_at                   TIMESTAMPTZ,
  PRIMARY KEY (message_id)
);
CREATE INDEX idx_messages_conv_created ON messages(conversation_id, created_at DESC);

CREATE TABLE circles (
  circle_id                    TEXT
  name                         TEXT
  description                  TEXT
  photo                        TEXT
  owner_id                     TEXT
  privacy                      TEXT
  created_at                   TIMESTAMPTZ
  updated_at                   TIMESTAMPTZ
  theme                        TEXT,
  PRIMARY KEY (circle_id)
);

CREATE TABLE circle_members (
  circle_id                    TEXT
  user_id                      TEXT
  role                         TEXT
  joined_at                    TIMESTAMPTZ,
  PRIMARY KEY (circle_id, user_id)
);

CREATE TABLE circle_invites (
  invite_id                    TEXT
  circle_id                    TEXT
  created_by                   TEXT
  invite_code                  TEXT
  expires_at                   TIMESTAMPTZ
  created_at                   TIMESTAMPTZ,
  PRIMARY KEY (invite_id)
);

CREATE TABLE circle_join_requests (
  request_id                   TEXT
  circle_id                    TEXT
  user_id                      TEXT
  status                       TEXT
  created_at                   TIMESTAMPTZ,
  PRIMARY KEY (request_id)
);

CREATE TABLE circle_messages (
  message_id                   TEXT
  circle_id                    TEXT
  sender_id                    TEXT
  content                      TEXT
  kind                         TEXT
  media                        TEXT
  reply_to                     TEXT
  edited                       BOOLEAN
  deleted_for_everyone         BOOLEAN
  read_by                      TEXT[]
  reactions                    JSONB
  created_at                   TIMESTAMPTZ,
  PRIMARY KEY (message_id)
);

CREATE TABLE stories (
  story_id                     TEXT
  user_id                      TEXT
  kind                         TEXT
  media                        TEXT
  caption                      TEXT
  is_private                   BOOLEAN
  viewers                      JSONB
  created_at                   TIMESTAMPTZ
  expires_at                   TIMESTAMPTZ
  story_reactions              JSONB
  text_x                       FLOAT
  text_y                       FLOAT
  text_color                   TEXT
  text_size                    INTEGER
  font_index                   INTEGER
  media_scale                  FLOAT
  media_x                      FLOAT
  media_y                      FLOAT
  music_id                     TEXT,
  PRIMARY KEY (story_id)
);
CREATE INDEX idx_stories_user_expires ON stories(user_id, expires_at);

CREATE TABLE notifications (
  notif_id                     TEXT
  user_id                      TEXT
  kind                         TEXT
  data                         JSONB
  read                         BOOLEAN
  created_at                   TIMESTAMPTZ,
  PRIMARY KEY (notif_id)
);
CREATE INDEX idx_notifications_user_created ON notifications(user_id, created_at DESC);

CREATE TABLE reports (
  report_id                    TEXT
  reporter_id                  TEXT
  reported_id                  TEXT
  conversation_id              TEXT
  category                     TEXT
  description                  TEXT
  status                       TEXT
  created_at                   TIMESTAMPTZ
  resolved_at                  TIMESTAMPTZ
  resolved_by                  TEXT,
  PRIMARY KEY (report_id)
);
CREATE INDEX idx_reports_status_created ON reports(status, created_at DESC);
CREATE INDEX idx_reports_reported ON reports(reported_id, created_at DESC);

CREATE TABLE appeals (
  appeal_id                    TEXT
  user_id                      TEXT
  name                         TEXT
  email                        TEXT
  message                      TEXT
  suspension_reason            TEXT
  status                       TEXT
  created_at                   TIMESTAMPTZ
  reviewed_at                  TIMESTAMPTZ
  reviewed_by                  TEXT,
  PRIMARY KEY (appeal_id)
);

CREATE TABLE push_tokens (
  user_id                      TEXT
  expo_push_token              TEXT
  device_name                  TEXT
  created_at                   TIMESTAMPTZ
  updated_at                   TIMESTAMPTZ,
  PRIMARY KEY (user_id, expo_push_token)
);

-- ── Reset auto-increment sequences ──────────────────────
SELECT setval('user_sessions_id_seq', COALESCE((SELECT MAX(id) FROM user_sessions), 1), (SELECT MAX(id) FROM user_sessions) IS NOT NULL);
SELECT setval('blocks_id_seq', COALESCE((SELECT MAX(id) FROM blocks), 1), (SELECT MAX(id) FROM blocks) IS NOT NULL);

-- ── Disable RLS (service-role key bypasses RLS anyway) ──
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE friend_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE friendships DISABLE ROW LEVEL SECURITY;
ALTER TABLE blocks DISABLE ROW LEVEL SECURITY;
ALTER TABLE conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE circles DISABLE ROW LEVEL SECURITY;
ALTER TABLE circle_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE circle_invites DISABLE ROW LEVEL SECURITY;
ALTER TABLE circle_join_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE circle_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE stories DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE appeals DISABLE ROW LEVEL SECURITY;
ALTER TABLE push_tokens DISABLE ROW LEVEL SECURITY;